### get blogs
GET http://localhost:3001/api/blogs

### create a blog
POST  http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pbW1hIiwiaWQiOiI2YTI0ZjM5YzQyMDM5ZmI3NDc3YmFhYzAiLCJpYXQiOjE3ODA4MDY1NjEsImV4cCI6MTc4MDgxMDE2MX0.mn8sf7Ces0dBv1aHGKpcS3vrwzYkPGjwHKhMRCRvxwE

{
  "title": "test 2",
  "author": "nimma",
  "url" : "test",
  "likes": 30
}

### delete a blog
DELETE  http://localhost:3001/api/blogs/6a24f3b642039fb7477baac3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pbW1hIiwiaWQiOiI2YTI0ZjM5YzQyMDM5ZmI3NDc3YmFhYzAiLCJpYXQiOjE3ODA4MDY1NjEsImV4cCI6MTc4MDgxMDE2MX0.mn8sf7Ces0dBv1aHGKpcS3vrwzYkPGjwHKhMRCRvxwE
