### make a user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "ro",
    "name": "Superuser",
    "password": "salainen"
}

### get all users
GET http://localhost:3001/api/users
