### get all persons
GET http://localhost:3001/api/persons 

### get single person
GET http://localhost:3001/api/persons/69de2ce8b9b9929d5aac3418

### get single person error 
GET http://localhost:3001/api/persons/69de2ce8b9b992d5aac3418 

### delete a single person 
DELETE  http://localhost:3001/api/persons/69dede9d4a15a4cce546eed6

### create a single person 
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "ndssda",
    "number": "67-6787"
}

### update a person
PUT  http://localhost:3001/api/persons/69deea7e98e589ffd7743cdf
Content-Type: application/json

{
    "name": "ni",
    "number": "9999"
}

### info
GET http://localhost:3001/info

### unkown
GET http://localhost:3001/unkown