import { useState } from 'react'
import axios from 'axios'
import SearchFilter from './components/SearchFilter'
import FilterCountries from './components/FilterCountries'

const showCountry = ({ name }) => { }

function App() {
  const [filter, setFilter] = useState('')
  const [countries, setCountries] = useState([
    "kuwait",
    "austria",
    "mayotte",
    "tunisia",
    "japan",
    "guyana",
    "saint helena, ascension and tristan da cunha",
    "saint martin",
    "guatemala",
    "venezuela",
    "french southern and antarctic lands",
    "cape verde",
    "azerbaijan",
    "guernsey",
    "kenya",
    "south sudan",
    "myanmar",
    "liechtenstein",
    "martinique",
    "australia",
    "costa rica",
    "palestine",
    "spain",
    "guinea-bissau",
    "åland islands",
    "sierra leone",
    "philippines",
    "togo",
    "russia",
    "haiti",
    "south korea",
    "samoa",
    "aruba",
    "afghanistan",
    "bouvet island",
    "bahamas",
    "georgia",
    "cayman islands",
    "north macedonia",
    "syria",
    "hong kong",
    "chile",
    "zimbabwe",
    "caribbean netherlands",
    "netherlands",
    "canada",
    "equatorial guinea",
    "eswatini",
    "oman",
    "united states",
    "heard island and mcdonald islands",
    "romania",
    "south africa",
    "mozambique",
    "trinidad and tobago",
    "bahrain",
    "republic of the congo",
    "lebanon",
    "réunion",
    "estonia",
    "bangladesh",
    "ethiopia",
    "peru",
    "south georgia",
    "ecuador",
    "vatican city",
    "mauritius",
    "american samoa",
    "saint pierre and miquelon",
    "cuba",
    "british indian ocean territory",
    "vietnam",
    "benin",
    "greece",
    "grenada",
    "belize",
    "china",
    "montenegro",
    "thailand",
    "guam",
    "comoros",
    "laos",
    "mali",
    "germany",
    "suriname",
    "gambia",
    "maldives",
    "tonga",
    "antigua and barbuda",
    "guinea",
    "curaçao",
    "panama",
    "papua new guinea",
    "new caledonia",
    "croatia",
    "palau",
    "united states virgin islands",
    "cambodia",
    "puerto rico",
    "french polynesia",
    "nicaragua",
    "colombia",
    "mauritania",
    "botswana",
    "fiji",
    "latvia",
    "svalbard and jan mayen",
    "bermuda",
    "uganda",
    "bosnia and herzegovina",
    "gabon",
    "chad",
    "cocos (keeling) islands",
    "kazakhstan",
    "pitcairn islands",
    "guadeloupe",
    "sudan",
    "dominica",
    "qatar",
    "barbados",
    "turkey",
    "denmark",
    "marshall islands",
    "yemen",
    "antarctica",
    "são tomé and príncipe",
    "turkmenistan",
    "north korea",
    "portugal",
    "eritrea",
    "gibraltar",
    "mongolia",
    "kosovo",
    "anguilla",
    "malawi",
    "tuvalu",
    "moldova",
    "brunei",
    "united states minor outlying islands",
    "finland",
    "ghana",
    "dominican republic",
    "northern mariana islands",
    "czechia",
    "morocco",
    "honduras",
    "israel",
    "madagascar",
    "luxembourg",
    "armenia",
    "turks and caicos islands",
    "falkland islands",
    "angola",
    "cyprus",
    "indonesia",
    "uzbekistan",
    "burundi",
    "albania",
    "saint barthélemy",
    "bolivia",
    "kyrgyzstan",
    "united arab emirates",
    "paraguay",
    "tanzania",
    "argentina",
    "pakistan",
    "nepal",
    "new zealand",
    "switzerland",
    "norfolk island",
    "sweden",
    "saint lucia",
    "uruguay",
    "mexico",
    "somalia",
    "montserrat",
    "norway",
    "seychelles",
    "nauru",
    "bhutan",
    "rwanda",
    "hungary",
    "slovenia",
    "sint maarten",
    "india",
    "french guiana",
    "italy",
    "singapore",
    "ireland",
    "andorra",
    "iceland",
    "micronesia",
    "faroe islands",
    "saint kitts and nevis",
    "niger",
    "france",
    "djibouti",
    "liberia",
    "taiwan",
    "jordan",
    "greenland",
    "libya",
    "kiribati",
    "cook islands",
    "lesotho",
    "monaco",
    "malaysia",
    "wallis and futuna",
    "saudi arabia",
    "bulgaria",
    "burkina faso",
    "brazil",
    "lithuania",
    "jersey",
    "algeria",
    "solomon islands",
    "sri lanka",
    "san marino",
    "united kingdom",
    "nigeria",
    "slovakia",
    "cameroon",
    "namibia",
    "egypt",
    "saint vincent and the grenadines",
    "belarus",
    "ukraine",
    "christmas island",
    "niue",
    "jamaica",
    "zambia",
    "senegal",
    "belgium",
    "central african republic",
    "iran",
    "iraq",
    "timor-leste",
    "isle of man",
    "macau",
    "el salvador",
    "malta",
    "poland",
    "serbia",
    "ivory coast",
    "western sahara",
    "dr congo",
    "tajikistan",
    "vanuatu",
    "tokelau",
    "british virgin islands"
  ])

  const filterCountries = filter ? countries.filter(c => c.includes(filter.toLowerCase())) : []
  return countries &&
    <div>
      <SearchFilter setFilter={setFilter} filter={filter} />
      <FilterCountries filterCountries={filterCountries} />
    </div>
}

export default App
