name: Zustand anecdotes pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CI: true

defaults:
  run:
    working-directory: ./part6/zustand-anecdotes

jobs:
  devlopment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: install dependencies
        run: npm install

      - name: test eslint
        run: npm run lint

      - name: run vitest
        run: npm run test

      - name: make build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:e2e

  notify_failure:
    needs: [devlopment_pipeline]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Build failed"
          color: 0xE74C3C

  notify_success:
    needs: [devlopment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Successful deployment"

  tag_release:
    needs: [devlopment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
